# Automation Tab
Automations_Tab:
  name: Automations
  view: yes
  icon: mdi:av-timer
  entities:
    - group.system_automations

# Automation Groups

system_automations:
  name: 'System Automations'
  entities:
    - automation.garage_door_power_toggle
    - automation.history_purge

