test:
  stage: test
  image: homeassistant/home-assistant

  script:
    - cd /usr/src/app
    - /usr/local/bin/python -m homeassistant --config /builds/willger/Home-Assistant/config --script check_config
    - echo $?
