spotify_playlist:
  name: 'Playlist:'
  options:
    - 'Your Top Songs 2017'
    - 'alt+(rock && roll)'
    - 'You boys smell like Flaers'
    - 'Pretty Intense Stuff'
  icon: mdi:spotify
spotify_source:
  name: 'Source:'
  options:
    - Upstairs Group
    - Bar speaker
    - Kitchen Home
    - Bedroom Speaker
    - Bathroom
    - Addy's Room
  initial: Upstairs Group
  icon: mdi:speaker-wireless
