## Harmony Remotes
sensor.tv_living_room:
  hidden: false
  icon: mdi:remote
sensor.tv_basement:
  hidden: false
  icon: mdi:remote

## Onkyo
sensor.onkyo_status:
  hidden: false
  icon: mdi:speaker

## Roku
sensor.roku_living_room:
  hidden: false
  icon: mdi:television-guide
sensor.roku_workout_room:
  hidden: false
  icon: mdi:television-guide

## Shield TV
sensor.sheild_tv:
  hidden: false
  icon: mdi:television-guide

