- name: goodbye_scene
  entities:
    group.living_room_lights:
      state: off
    switch.cabinet_switch:
      state: off
    light.bedroom:
      state: off
    group.basement_lights:
      state: off
