- name: good_night_scene
  entities:
    group.living_room_lights:
      state: off
    light.bedroom:
      state: on
    light.office_lamp:
      state: off
    group.basement_lights:
      state: off
    light.cabinet_lights:
      state: off
    light.dining_room_light:
      state: off
    light.kitchen_light:
      state: off
    switch.hall_nl:
      state: on
