- name: hall_nl_scene
  entities:
    light.right_lamp:
      state: on
      brightness: 50
    light.left_lamp:
      state: on
      brightness: 50
    switch.cabinet_switch:
      state: on
- name: hall_nl_off_scene
  entities:
    light.right_lamp:
      state: off
    light.left_lamp:
      state: off
    switch.cabinet_switch:
      state: off
- name: basement_nl_scene
  entities:
    light.basement_entry:
      state: on
      brightness: 50
    light.basement_lamp:
      state: on
      brightness: 50
    light.corner_light:
      state: on
      brightness: 50
- name: basement_nl_off_scene
  entities:
    light.basement_entry:
      state: off
    light.basement_lamp:
      state: off
    light.corner_light:
      state: off