- name: hall_nl_scene
  entities:
    light.living_room:
      state: on
      brightness: 50
      kelvin: 3500
    light.cabinet_lights:
      state: on

- name: basement_nl_scene
  entities:
    light.basement_entry:
      state: on
      brightness: 50
    light.basement_lamp:
      state: on
      brightness: 50
    light.corner_light:
      state: on
      brightness: 50
