switch.porch_lights_switch:
  expose: true
  name: 'Porch Lights'
light.basement_entry:
  expose: true
light.bedroom_lamp:
  expose: true
light.left_lamp:
  expose: true
light.right_lamp:
  expose: true
light.beths_lamp:
  expose: true
light.ryans_lamp:
  expose: true
light.addys_lamp:
  expose: true
  name: "Addy's Lamp"
light.sophies_lamp:
  expose: true
  name: "Sophie's Lamp"
light.basement_lamp:
  expose: true
light.bar_lights:
  expose: true
  name: 'Bar Lights'
light.corner_light:
  expose: true
  name: 'Corner Light'
switch.aeotec_relay_dining_room_light:
  expose: true
  name: 'Dining Room Light'
switch.aeotec_relay_kitchen_light:
  expose: true
  name: 'Kitchen Light'
switch.garage_door_opener:
  expose: true
  name: 'Garage Door'
switch.cabinet_switch:
  expose: true
  name: 'Cabinet Lights'