switch.porch_lights_switch:
  expose: true
  name: 'Porch Lights'
light.cabinet_lights:
  expose: true
light.basement_entry:
  expose: true
light.bedroom_lamp:
  expose: true
light.left_lamp:
  expose: true
light.right_lamp:
  expose: true
light.beths_lamp:
  expose: true
light.ryans_lamp:
  expose: true
light.basement_lamp:
  expose: true
light.bar_lights:
  expose: true
  name: 'Bar Lights'
light.office_lamp:
  expose: true
  name: 'Office Lamp'
switch.aeotec_relay_dining_room_light:
  expose: true
  name: 'Dining Room Light'
switch.aeotec_relay_kitchen_light:
  expose: true
  name: 'Kitchen Light'
switch.basement_nl:
  expose: true
  name: 'Basement NL'
switch.hall_nl:
  expose: true
  name: 'Hall NL'
switch.garage_door_opener:
  expose: true
  name: 'Garage Door'
