# Hall NL Simulated switch
# Ties the Hall NL automations to one switch.
  - platform: template
    switches:
      hall_nl:
        friendly_name: 'Hall NL'
        value_template: '{{ is_state("group.hall_nl_app", "on") }}'
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.hall_nl_app
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.hall_nl_app
  # Basement NL Simulated switch
  # Ties the Basement NL automations to one switch.
      basement_nl:
        friendly_name: 'Basement NL'
        value_template: '{{ is_state("group.basement_nl_app", "on") }}'
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.basement_nl_app
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.basement_nl_app
          
  # Guest Mode switch. Used overide functions of the home/away presence detection for when guests are over. 
      basement_nl:
        friendly_name: 'Guest Mode'
        value_template: '{{ is_state("input_select.home_presence", "Guest") }}'
        turn_on:
          service: input_select.select_option
          data:
            entity_id: "input_select.home_presence"
            option:"Guest"
        turn_off:
          service: input_select.select_previous
          entity_id: input_select.home_presence

#  - platform: tplink
#    name: TP-Link Switch
#    host: 192.168.1.118

#- platform: zoneminder
#  command_on: Modect
#  command_off: Monitor
