# Hall NL Simulated switch
# Ties the Hall NL automations to one switch.
  - platform: template
    switches:
      hall_nl:
        friendly_name: 'Hall NL'
        value_template: '{{ is_state("group.hall_nl_app", "on") }}'
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.hall_nl_app
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.hall_nl_app
  # Basement NL Simulated switch
  # Ties the Basement NL automations to one switch.
      basement_nl:
        friendly_name: 'Basement NL'
        value_template: '{{ is_state("group.basement_nl_app", "on") }}'
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.basement_nl_app
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.basement_nl_app
          
  # Guest Mode switch. Used overide functions of the home/away presence detection for when guests are over. 
      guest_mode_switch:
        friendly_name: 'Guest Mode'
        value_template: '{{ is_state_attr('switch.guest_mode_switch', 'icon', 'mdi:account-off-outline') }}'
        turn_on:
          service: input_number.increment
          data:
            entity_id: input_number.humans
        turn_off:
          service: input_number.decrement
          data:
            entity_id: input_number.humans

# Cabinet lights: Controlled by GE switch only. 
      cabinet_switch:
        friendly_name: "Cabinet Switch"
        value_template: "{{ is_state('switch.ge_toggle_switch', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: light.cabinet_lights
        turn_off:
          service: switch.turn_off
          data:
            entity_id: light.cabinet_lights

#  - platform: tplink
#    name: TP-Link Switch
#    host: 192.168.1.118

#- platform: zoneminder
#  command_on: Modect
#  command_off: Monitor
