# Hall NL Simulated switch
# Ties the Hall NL automations to one switch.
  - platform: template
    switches:
      hall_nl:
        friendly_name: 'Hall NL'
        value_template: '{{ is_state("input_boolean.hall_nl", "on") }}'
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.hall_nl
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.hall_nl
  # Basement NL Simulated switch
  # Ties the Basement NL automations to one switch.
      basement_nl:
        friendly_name: 'Basement NL'
        value_template: '{{ is_state("input_boolean.basement_nl", "on") }}'
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.basement_nl
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.basement_nl
          
  # Guest Mode switch. Used overide functions of the home/away presence detection for when guests are over. 
      guest_mode_switch:
        friendly_name: 'Guest Mode'
        value_template: '{{ is_state("input_boolean.guest_mode", "on") }}'
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.guest_mode
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.guest_mode

# Cabinet lights: Controlled by GE switch only. 
      cabinet_switch:
        friendly_name: "Cabinet Switch"
        value_template: "{{ is_state('switch.ge_toggle_switch', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: light.cabinet_lights
        turn_off:
          service: switch.turn_off
          data:
            entity_id: light.cabinet_lights

#  - platform: tplink
#    name: TP-Link Switch
#    host: 192.168.1.118

#- platform: zoneminder
#  command_on: Modect
#  command_off: Monitor
