# If the dinning or kitchen light turn on change the Living Room lights to Daylight.
- alias: 'Sync Lights ON'
  trigger:
    platform: state
    entity_id: switch.aeotec_relay_kitchen_light, switch.aeotec_relay_dining_room_light
    to: 'on'
    from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.living_room
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: scene.turn_on
      entity_id: scene.lr_daylight

- alias: 'Sync Lights OFF'
  trigger:
    platform: state
    entity_id: switch.aeotec_relay_kitchen_light, switch.aeotec_relay_dining_room_light
    to: 'off'
    from: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.living_room
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: switch.aeotec_relay_kitchen_light
        state: 'off'
      - condition: state
        entity_id: switch.aeotec_relay_dining_room_light
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.lr_warmlight
