- alias: 'Set Spotify Volume'
  trigger:
    platform: state
    entity_id: input_slider.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_slider.spotify_volume.state  }}'
