hass_ip: Test
api_password: Test
home_url: Test

home_latitude: Test
home_longitude: Test

db_url: Test

mqtt_username: Test
mqtt_password: Test

# nest
nest_client_id: Test
nest_client_secret: Test

# ifttt
ifttt_key: Test

# Alarm Control Panel
alarm_code: Test

# Firestieck IP
firetv_ip: Test

# Highway Camera
carmichael_cam_url: Test
bridge_cam_url: Test

# DuckDNS
dns_domain: Test
dns_token: Test

# Google Assistant
goog_project_id: Test
goog_client_id: Test
goog_access_token: Test
goog_api_key: Test

# Spotify App
spotify_client_id: Test
spotify_secret: Test

#Slack API KEY
slack_api_key: Test

# Open Weather Map
openweathermap_api_key: Test

#zwave
zwave_network_key: Test
