# Any door is open
#  doors_group_alert:
#    name: 'Doors Status' 
#    done_message: Doors are closed.
#    entity_id: group.door_states
#    state: 'open'
#    repeat: 30
#    can_acknowledge: True
#    skip_first: False
#    notifiers: 
#      - persistent_notification
#      - maxthedog
