# Entry Garagbe Door (Z-Wave Plus Recessed Door/Window Sensor)
- platform: template
  sensors:
    entry_garage_door:
      friendly_name: "Entry Garage Door"
      value_template: >-
        {%if is_state("sensor.entry_garage_door_access_control","22") %}
        open
        {% else %}
        closed
        {% endif %}
      icon_template: >-
        {%if is_state("sensor.entry_garage_door_access_control","22") %}
        mdi:door-open
        {% else %}
        mdi:door
        {% endif %}
    entry_garage_door_battery:
      friendly_name: "Entry Garage Door Battery"
      value_template: >-
        {{ states.zwave.entry_garage_door.attributes.battery_level|default(0) }}
      icon_template: >-
        {%if is_state("zwave.entry_garage_door","sleeping") %}
          {% set battery_level = states.zwave.entry_garage_door.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {%else%}
          mdi:battery
        {%endif%}

# Back Door (Z-Wave Plus Recessed Door/Window Sensor)
- platform: template
  sensors:
    back_door:
      friendly_name: "Back Door"
      value_template: >-
        {%if is_state("sensor.back_door_access_control","22") %}
        open
        {% else %}
        closed
        {% endif %}
      icon_template: >-
        {%if is_state("sensor.back_door_access_control","22") %}
        mdi:door-open
        {% else %}
        mdi:door
        {% endif %}
    back_door_sensor_battery:
      friendly_name: "Back Door Battery"
      value_template: >-
        {{ states.zwave.back_door.attributes.battery_level|default(0) }}
      icon_template: >-
        {%if is_state("zwave.back_door","sleeping") %}
          {% set battery_level = states.zwave.entry_garage_door.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {%else%}
          mdi:battery
        {%endif%}

# Front Door (Z-Wave Plus Recessed Door/Window Sensor)
- platform: template
  sensors:
    front_door:
      friendly_name: "Front Door"
      value_template: >-
        {%if is_state("sensor.front_door_access_control","22") %}
        open
        {% else %}
        closed
        {% endif %}
      icon_template: >-
        {%if is_state("sensor.front_door_access_control","22") %}
        mdi:door-open
        {% else %}
        mdi:door
        {% endif %}
    front_door_sensor_battery:
      friendly_name: "Front Door Battery"
      value_template: >-
        {{ states.zwave.front_door.attributes.battery_level|default(0) }}
      icon_template: >-
        {%if is_state("zwave.front_door","sleeping") %}
          {% set battery_level = states.zwave.entry_garage_door.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {%else%}
          mdi:battery
        {%endif%}

# Patio Door (HKZW-DWS01)
- platform: template
  sensors:
    patio_door:
      friendly_name: "Patio Door"
      value_template: >-
        {%if is_state("sensor.patio_door_access_control", "22") %}
        open
        {% else %}
        closed
        {% endif %}
      icon_template: >-
        {%if is_state("sensor.patio_door_access_control","22") %}
        mdi:door-open
        {% else %}
        mdi:door
        {% endif %}
    patio_door_sensor_battery:
      friendly_name: "Patio Door Sensor Battery"
      value_template: >-
        {{ states.zwave.patio_door.attributes.battery_level|default(0) }}
      icon_template: >-
        {%if is_state("zwave.patio_door","sleeping") %}
          {% set battery_level = states.zwave.entry_garage_door.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {%else%}
          mdi:battery
        {%endif%}
