- platform: nut
  name: UPS
  host: !secret nut_server_ip
  port: 3493
  username: !secret nut_server_un
  password: !secret nut_server_pw
  resources:
    - battery.charge
    - battery.voltage
    - input.voltage
    - ups.load
    - ups.timer.reboot
    - ups.timer.shutdown
    
- platform: rest
  name: HA Upstream
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  value_template: '{{ value_json.tag_name }}'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor
    
- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  name: HA upstream type
  value_template: '{{ value_json["prerelease"] }}'
  scan_interval: 3600

- platform: version