- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: command_line
  name:  Hass Latest Docker
  command:  curl -s -L https://registry.hub.docker.com/v2/repositories/homeassistant/raspberrypi2-homeassistant/tags/ | grep -Eo '"Version":\s"[0-9.]*"' | head -1 | sed -e "s/\"name\":\s\"/${replace}/g" | sed -e "s/\"/${replace}/g"
  scan_interval: 28800