- platform: nut
  name: UPS
  host: !secret nut_server_ip
  port: 3493
  username: !secret nut_server_un
  password: !secret nut_server_pw
  resources:
    - battery.charge
    - battery.voltage
    - input.voltage
    - ups.load
    - ups.timer.reboot
    - ups.timer.shutdown
    
- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  name: HA upstream
  value_template: "{{ value_json['name'] }}"
  scan_interval: 3600
- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  name: HA upstream type
  value_template: "{{ value_json['prerelease'] }}"
  scan_interval: 3600

- platform: version