- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: command_line
  name: Hass Latest Docker
  command: >-
    curl -sS "https://registry.hub.docker.com/v2/repositories/homeassistant/home-assistant/tags/" | grep -o '"name": "0[^"]*"' | sort -r | head -1 | sed 's/[^0-9.]//g'
  scan_interval: 28800