- platform: nut
  name: UPS
  host: !secret nut_server_ip
  port: 3493
  username: !secret nut_server_un
  password: !secret nut_server_pw
  resources:
    - battery.charge
    - battery.voltage
    - input.voltage
    - ups.load
    - ups.timer.reboot
    - ups.timer.shutdown
    
- platform: rest
  resource: https://pypi.python.org/pypi/homeassistant/json
  name: HA upstream
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600

- platform: version