- platform: nest
  monitored_conditions:
     - 'temperature'
     - 'target'
     - 'humidity'
     - 'operation_mode'
     - 'co_status'
     - 'smoke_status'

#- platform: wunderground
#  api_key: !secret weather_api_key
#  monitored_conditions:
#    - alerts
    #- dewpoint_f
    #- dewpoint_string
#    - feelslike_f
    #- feelslike_string
    #- heat_index_f
    #- heat_index_string
    #- elevation
    #- location
    #- observation_time
    #- precip_1hr_in
    #- precip_1hr_string
#    - precip_today_in
    #- precip_today_string
    #- pressure_in
    #- pressure_trend
#    - relative_humidity
    #- station_id
    #- solarradiation
    #- temperature_string
#    - temp_f
    #- UV
    #- visibility_mi
#    - weather
    #- wind_degrees
    #- wind_dir
    #- wind_gust_mph
    #- wind_mph
    #- wind_string
