# Turn NL app ON at SUNSET and OFF at SUNRISE
- alias: 'App Toggle Basement Night Light'
  trigger:
    - platform: sun
      event: sunrise
    - platform: sun
      event: sunset
  action:
    service_template: >-
      {%- if is_state("sun.sun", "above_horizon") -%}
      homeassistant.turn_on
      {%- else -%}
      homeassistant.turn_off
      {%- endif %}
    entity_id: switch.basement_nl