# Toggle Off Garage Door outlet after it's turned on
- alias: 'Garage Door Power Toggle'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.garage_door_opener
    to: 'on'
    for: 00:00:10
  action:
    service: homeassistant.turn_off
    entity_id: switch.garage_door_opener
