- alias: ha_start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: automation.trigger
      entity_id: automation.porch_lights_night_check
    - service: homeassistant.turn_off
      entity_id:
        - group.hall_nl_app
        - group.basement_nl_app
    - service: notify.maxthedog
      data:
        message: 'Home-Assistant started.'
