#Turn on Porch Lights on weekdays when home.
- alias: '5AM Porch Lights'
  trigger:
    platform: time
    at: '05:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_select.home_presence
        state: 'Home'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.porch_lights_switch
    - service: homeassistant.turn_off
      entity_id: automation.porch_lights_minder
    - service: homeassistant.turn_off
      entity_id: automation.door_to_light_trigger

#Turn off Porch Lights when the sun comes up.
- alias: 'Sunrise Porch Lights'
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: switch.porch_lights_switch

#Turn On porch lights at sunset when away OR the Garage Door is open.
- alias: 'Sunset Porch Lights'
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: numeric_state
    entity_id: sensor.home_count
    below: 2
  action:
    - service: homeassistant.turn_on
      entity_id: switch.porch_lights_switch

- alias: 'Activate Porch Lights Minder'
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.porch_lights_minder
        - automation.door_to_light_trigger
