# Let me know if I left the garage door open at night
- alias: 'Garage Door Reminder'
  initial_state: 'on'
  trigger:
    platform: time
    hours: '20'
    minutes: '00'
    seconds: '00'
  condition:
    condition: state
    entity_id: sensor.garage_door
    state: open
  action:
    - service: notify.maxthedog
      data:
        message: 'You left the Garage Door open.'

### start Porch Lights Minder at Sunset
- alias: 'Activate PLM at sunset'
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.porch_lights_minder

- alias: 'Deactivate PLM at sunrise'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: group.porch_lights_minder
