- platform: template
    covers:
      garage_door_cover:
        friendly_name: "Garage Door Cover"
        position_template: >-
          {% if is_state("binary_sensor.garage_door_sensor", "on") %}
          1
          {% else %}
          0
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door_opener
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door_opener
        icon_template: >-
          {%if is_state("binary_sensor.garage_door_sensor", "on") %}
          mdi:garage-open
          {% else %}
          mdi:garage
          {% endif %}
