######## Z-Wave ############
# Entry Way Motion Sensor (KFR-ZP3102US-5)
- platform: template
  sensors:
    entry_way_motion:
      friendly_name: "Entry Way Motion"
      value_template: >-
        {%if is_state("sensor.entry_way_motion_sensor_burglar", "8") %}
        active
        {% else %}
        inactive
        {% endif %}
    entry_way_sensor_battery:
      friendly_name: "Entry Way Sensor Battery"
      value_template: >-
        {{ states.zwave.entry_way_motion_sensor.attributes.battery_level|default(0) }}
      icon_template: >-
        {% set battery_level = states.zwave.entry_way_motion_sensor.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if is_state('states.zwave.entry_way_motion_sensor.attributes.battery_level', 'unknown') %}
          mdi:battery-alert
        {% elif battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

# Kitchen Motion Sensor (KFR-ZP3102US-5)
- platform: template
  sensors:
    kitchen_motion:
      friendly_name: "Kitchen Motion"
      value_template: >-
        {%if is_state("sensor.kitchen_motion_sensor_burglar", "8") %}
        active
        {% else %}
        inactive
        {% endif %}
    kitchen_sensor_battery:
      friendly_name: "Kitchen Sensor Battery"
      value_template: >-
        {{ states.zwave.kitchen_motion_sensor.attributes.battery_level|default(0) }}
      icon_template: >-
        {% set battery_level = states.zwave.kitchen_motion_sensor.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if is_state('zwave.kitchen_motion_sensor.attributes.battery_level', 'unknown') %}
          mdi:battery-alert
        {% elif battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

# Hall Motion Sensor (KFR-ZP3102US-5)
- platform: template
  sensors:
    hall_motion:
      friendly_name: "Hall Motion"
      value_template: >-
        {%if is_state("sensor.hall_motion_sensor_burglar", "8") %}
        active
        {% else %}
        inactive
        {% endif %}
    hall_sensor_battery:
      friendly_name: "Hall Sensor Battery"
      value_template: >-
        {{ states.zwave.hall_motion_sensor.attributes.battery_level|default(0) }}
      icon_template: >-
        {% set battery_level = states.zwave.hall_motion_sensor.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

# Basement Motion Sensor (zooz zse02)
- platform: template
  sensors:
    basement_motion:
      friendly_name: "Basement Motion"
      value_template: >-
        {%if is_state("sensor.basement_motion_sensor_burglar", "8") %}
        active
        {% else %}
        inactive
        {% endif %}
    basement_motion_battery:
      friendly_name: "Basement Sensor Battery"
      value_template: >-
        {{ states.zwave.patio_door.attributes.battery_level|default(0) }}
      icon_template: >-
        {% set battery_level = states.zwave.patio_door.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}


# Garage Door Tilt Sensor (ecolink TILT-ZWAVE2)
- platform: template
  sensors:
    garage_door:
      friendly_name: "Garage Door"
      value_template: >-
        {%if is_state("binary_sensor.garage_door_sensor", "on") %}
        open
        {% else %}
        closed
        {% endif %}
      icon_template: >-
        {%if is_state("binary_sensor.garage_door_sensor", "on") %}
        mdi:garage-open
        {% else %}
        mdi:garage
        {% endif %}
    garage_door_sensor_battery:
      friendly_name: "Garage Door Battery"
      value_template: >-
        {{ states.zwave.garage_door.attributes.battery_level|default(0) }}
      icon_template: >-
        {% set battery_level = states.zwave.garage_door.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

#ZoneMinder
#- platform: zoneminder
#  include_archived: false
#  monitored_conditions: day
