- platform: template
  sensors:
    home_presence:
      value_template: '{{ states.input_select.home_presence.state }}'
      friendly_name: 'Home Presence'
    home_count:
      friendly_name: "Home Count"
      value_template: >-
        {% if is_state("sensor.home_presence", "Away")  -%}
        0
        {%- elif is_state("sensor.home_presence", "Home") and (states("device_tracker.ryan_phone")!="home" or states("device_tracker.beth_phone")!="home") -%}
        1
        {%- elif is_state("sensor.home_presence", "Home") and (states("device_tracker.ryan_phone")=="home" or states("device_tracker.beth_phone")=="home") -%}
        2
        {%- endif %}
    thermostat_upstairs_away_mode:
      value_template: '{{ states.climate.upstairs.attributes.away_mode }}'
      friendly_name: 'Nest Away Mode'
    living_room_tv:
      value_template: >-
        {% if is_state('remote.living_room', 'on') %}
        {{ states.remote.living_room.attributes.current_activity }}
        {% else %}
        {{ states('remote.living_room')}}
        {% endif %}
      friendly_name: 'Living Room TV'
    family_room_tv:
      value_template: >-
        {% if is_state('remote.family_room', 'on') %}
        {{ states.remote.family_room.attributes.current_activity }}
        {% else %}
         {{ states('remote.family_room')}}
        {% endif %}
      friendly_name: 'Family Room TV'
    bedroom_tv:
      value_template: >-
        {% if is_state('remote.bedroom', 'on') %}
        {{ states.remote.bedroom.attributes.current_activity }}
        {% else %}
         {{ states('remote.bedroom')}}
        {% endif %}
      friendly_name: 'Bedroom TV'
